version: '3'
services:
  hacktoday:
    container_name: safe_calc
    restart: always
    build:
      context: .
      args:
        binary: server.py
    ports:
      - "18000:5000" # exposed:local
    read_only: true
