version: '3'
services:
  hacktod:
    container_name: DejaVu
    restart: always
    build:
      context: .
      args:
        binary: server.py
    ports:
      - "18000:5000" # exposed:local
    read_only: true
